# Generated by Django 5.2.12 on 2026-03-24 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('choose_correct', "To'g'ri so'zni tanlash"), ('fill_blank', "Bo'sh joy to'ldirish"), ('matching', 'Moslashtirish')], max_length=20)),
                ('instruction', models.TextField()),
                ('content', models.JSONField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.lesson')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
