# Generated by Django 5.2.12 on 2026-04-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='audio_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='has_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('choose_correct', "To'g'ri so'zni tanlash"), ('fill_blank', "Bo'sh joy to'ldirish"), ('matching', 'Moslashtirish'), ('listening', 'Listening'), ('speaking', 'Speaking')], max_length=20),
        ),
    ]
