# Generated by Django 5.2.12 on 2026-04-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0004_level_remove_lesson_difficulty_lesson_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.level'),
        ),
    ]
