# Generated by Django 5.2.12 on 2026-04-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('a1', 'A1 Beginner'), ('a2', 'A2 Elementary'), ('b1', 'B1 Pre-Intermediate'), ('b2', 'B2 Intermediate'), ('c1', 'C1 Upper-Intermediate'), ('c2', 'C2 Advanced'), ('ielts', 'IELTS')], max_length=10, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='lesson',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='courses.level'),
        ),
    ]
